name: Update BLS Benchmarks

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  update-bls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run update script
        run: node scripts/update-bls-benchmarks.js
      - name: Set up authenticated git
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -x
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          echo "After set-url, git remote -v:"
          git remote -v

      - name: Debug git remote and user
        run: |
          git remote -v
          git config --get user.name
          git config --get user.email
          echo "Current branch: $(git branch --show-current)"
          echo "GitHub ref: ${{ github.ref }}"

      - name: Commit and push changes
        run: |
          git add public/data/bls-benchmarks-hierarchical.json
          git commit -m 'Update BLS benchmarks (automated)' || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
